### ISSUE TITLE
Bookmarklet: 500 Internal Server Error

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1009]
@jcuanm I cannot use the bookmarklet function. It results in a 500 message.  
Please let me know if you modifying the bookmarklet.
![screen shot 2015-10-15 at 2 15 37 pm](https://cloud.githubusercontent.com/assets/8831502/10523297/b5fbe74c-7347-11e5-89db-f5327a98d48c.png)

**Comment by meeshmon** [comment]
@horak @jcuanm can you guys investigate this?
probably happened after the last merge

**Comment by spacemansteve** [comment]
The log file at /var/www/jda/app/logs/prod.log contains many entries about bookmarklet:

[2015-10-19 22:24:44] request.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /bookmarklet" (uncaught exception) at /var/www/jda/app/cache/prod/classes.php line 5219 [] []

This is in the function RouterListener.onKernelRequest.  The exception is handled by:
catch (ResourceNotFoundException $e) {
            $message = sprintf('No route found for "%s %s"', $request->getMethod(), $request->getPathInfo());

**Comment by spacemansteve** [comment]
/var/www/jda/src/JDA/CoreBundle/Resources/config/routing.yml contains:
bookmarklet:
    pattern:    /{_locale}/bookmarklet/
    defaults:  { _controller: JDACoreBundle:Bookmarklet:index, _locale: ja }
    requirements:
        _locale: en|ja

**Comment by rchen152** [comment]
The bookmarklet displays properly in dev:
http://jdarchive.org/widget
gives 500 Internal Server Error but
http://dev.jdarchive.org/rebecca/web/widget
looks fine.

(The url needs to be changed manually, since the code currently leaves out the "[name]/web/" part when trying to open the bookmarklet in dev - this needs to be fixed.)

**Comment by rchen152** [comment]
Submitted a patch (https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/pull/1012) that should fix this.  As int turns out, the reason that the bookmarklet was displaying properly on my dev instance is that I hadn't yet pulled the latest code.  Once I did that, I got the 500 Internal Server Error along with a helpful debug message that told me that there was an illegal byte order mark at the beginning of a file.  (If at the command line, you type
  less /var/www/[name]/src/JDA/CoreBundle/Resources/views/Widget/widget.html.twig
you'll see <U+FEFF> on the first line.)  I removed it by opening the file with Emacs, changing the file encoding to utf-8 (see http://stackoverflow.com/questions/3859274/removing-byte-order-marks-boms-using-emacs), and deleting and re-inserting the first blank line in the file.

**Comment by horak** [comment]
Cool, I just merged this and will push live soon.

**Comment by meeshmon** [comment]
still cannot use the bookmarklet. Getting the same 500 internal Server Error.

**Comment by rchen152** [comment]
I think the fix has been merged but not pushed to production, so the changes aren't live yet.

**Comment by meeshmon** [comment]
Ok cool. Thanks Rebecca for the note.

**Comment by horak** [comment]
Live now! Let me know if it persists
