### ISSUE TITLE
Many items have NULL for media creation date - replace with item creation date

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#530]

**Comment by ebensing** [comment]
as mentioned in the email, these items have their media_create_date set to NULL. We need to decide how to proceed with these items.

**Comment by nickkapur** [comment]
Okay, let's discuss this at our meeting on Thursday.

**Comment by nickkapur** [comment]
It seems impossible to change the date in the admin view.

**Comment by ebensing** [comment]
fixed

**Comment by nickkapur** [comment]
@ebensing The date search still seems to be not working right. Newly submitted and published websites still show up in the sort as oldest, despite having a recent date. So the problem is still there. Should I reopen this issue?

**Comment by nickkapur** [comment]
This is definitely not fixed yet. Items submitted recently keep displaying with today's date and time. Reopening this issue.
